# Generated by Django 6.0 on 2025-12-25 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(help_text='URL категории (латиница, без пробелов)', max_length=100, unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Изображение')),
                ('order', models.PositiveIntegerField(default=0, help_text='Порядок отображения (меньше = выше)', verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, help_text='Отображать категорию на сайте', verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(help_text='URL продукта (латиница, без пробелов)', max_length=200, unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, help_text='Состав, особенности', verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=0, help_text='Цена в сумах', max_digits=10, verbose_name='Цена')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Изображение')),
                ('weight', models.CharField(blank=True, help_text='Например: 250г или 330мл', max_length=50, verbose_name='Вес/Объём')),
                ('pieces', models.PositiveSmallIntegerField(blank=True, help_text='Количество штук в порции (для роллов)', null=True, verbose_name='Количество штук')),
                ('is_available', models.BooleanField(default=True, help_text='Доступен для заказа', verbose_name='В наличии')),
                ('is_popular', models.BooleanField(default=False, help_text='Показывать в блоке популярных', verbose_name='Популярное')),
                ('is_new', models.BooleanField(default=False, help_text='Показывать метку "Новинка"', verbose_name='Новинка')),
                ('order', models.PositiveIntegerField(default=0, help_text='Порядок в категории (меньше = выше)', verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='menu.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ['category', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлен')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='menu.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Избранное',
                'verbose_name_plural': 'Избранное',
                'ordering': ['-created_at'],
                'unique_together': {('customer', 'product')},
            },
        ),
    ]
