# Generated by Django 6.0 on 2025-12-25 14:57

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone', models.CharField(help_text='Формат: +998901234567', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Введите корректный номер телефона (10-15 цифр)', regex='^\\+?[0-9]{10,15}$')], verbose_name='Номер телефона')),
                ('telegram_chat_id', models.CharField(blank=True, help_text='ID чата для уведомлений клиенту', max_length=50, verbose_name='Telegram Chat ID')),
                ('bonus_balance', models.PositiveIntegerField(default=0, help_text='Бонусные баллы клиента', verbose_name='Бонусный баланс')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='SavedAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('home', 'Дом'), ('work', 'Работа'), ('other', 'Другое')], default='home', max_length=50, verbose_name='Название')),
                ('custom_name', models.CharField(blank=True, help_text='Если выбрано "Другое"', max_length=100, verbose_name='Своё название')),
                ('address', models.TextField(help_text='Полный адрес доставки', verbose_name='Адрес')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Широта')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Долгота')),
                ('is_default', models.BooleanField(default=False, help_text='Использовать этот адрес по умолчанию', verbose_name='По умолчанию')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_addresses', to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Сохранённый адрес',
                'verbose_name_plural': 'Сохранённые адреса',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
    ]
