# Generated by Django 6.0 on 2025-12-25 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_token', models.CharField(help_text='Токен бота от @BotFather', max_length=100, verbose_name='Bot Token')),
                ('chat_id', models.CharField(help_text='ID группы/чата для уведомлений о заказах', max_length=50, verbose_name='Chat ID ресторана')),
                ('is_active', models.BooleanField(default=True, help_text='Отправлять уведомления в Telegram', verbose_name='Активен')),
                ('notify_customer', models.BooleanField(default=False, help_text='Отправлять уведомления клиентам о статусе заказа', verbose_name='Уведомлять клиента')),
                ('welcome_message', models.TextField(blank=True, default='Добро пожаловать в Suwi! Здесь вы будете получать уведомления о статусе ваших заказов.', help_text='Сообщение при подключении клиента к уведомлениям', verbose_name='Приветственное сообщение')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Настройки Telegram',
                'verbose_name_plural': 'Настройки Telegram',
            },
        ),
    ]
